### ISSUE TITLE
Donator Items not given after donating.

### ISSUE THREAD

**Issue by IVIUSE** [joshmoni/Joshmonis-Modpacks#11]
Hi! 
I just bought the "miner" donation for the middle earth server, but when I logged on, the items (specifically the pick and sword) were not in my inventory. I have access to other donator features, but I didn't receive the pick or sword.

**Comment by joshmoni** [comment]
Hmm ill look into that now...

Date: Fri, 2 Jan 2015 12:40:06 -0800
